global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ticket-booking-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ticket-backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
